version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3050:80"
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "9229:9229"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PORT=4000
      - NODE_ENV=development
